### PR TITLE
trigger github actions

### PR DESCRIPTION
**Pull request by mattonem**
https://github.com/PharoJS/PharoJS/issues/122

Most Web-based test cases okay.

NodeJS tests are still failing as node cannot find the ws module , despite `npm install -g ws`. Any idea?

One legitimate bug in PjDateAndTimeTest. 
When printing DateAndTime with a 0 offset... Pharo prints it as `+0`, Browsers prints it as `-0`.

### CODE REVIEW

**Comment by mattonem** [comment]
https://github.com/PharoJS/PharoJS/issues/132 -> issue related to PjDateAndTimeTest.

**Comment by bouraqadi** [comment]
I don't think the date issue is related

**Comment by mattonem** [comment]
For now only the following test cases are still failing on the Github VM: ` #PhxBridgedDateAndDateAndTimeTests, #PjDateAndTimeTest, #PjMinimalNodeApplicationTest, #PjHtmlCollectionTest`
With #133, `#PjDateAndTimeTest` should start working.

**Comment by mattonem** [comment]
For now (with ExpressJS) only the following test cases are still failing on the Github VM: `PjMinimalNodeApplicationTest, PjHtmlCollectionTest, PjHelloWorldExpressClientAppTest, PjBridgeTestCase, PjNodeAppExportTest, PhxBridgedDateAndDateAndTimeTests, PjHelloWorldExpressAppApiTest`

**Pull request closed without merging**
