### PR TITLE
Proposing a new way of starting BridgeClient. 

### PR DESCRIPTION
**Pull request by mattonem**
On my system, loading file://path/index.js in the browser load a corrupted file (Apple M1 is full of mysteries...). 
With this approach, serving the files is delegated to the bridge itself. 
It also give more flexibility as the server is running on http://localhost:bridgePort, we could delegate the provisioning of the WebBrowser to a remote device (via adb command on Android for instance).

This is only a proposition. 
If you think this could be a useful addition to PharoJS Base Bridge, I'll spend more time on the implementation and building a proper testing suite for this bridge.

### CODE REVIEW

**Comment by bouraqadi** [comment]
Thank you Max for the contribution. The idea sounds good. We've loaded the PR into `pharo10` branch and referenced your client in `PjFileBasedWebApp`. 

```st
PjFileBasedWebApp>>#bridgeClientClass
	<pharoJsSkip>
	
	^ PjBridgeServedFileBasedBrowserBridgeClient
``` 

Here are some comments based on our tests: 
-  11 errors (see screenshot)
Screenshot 2022-10-05 at 15 55 26

- Filenames (index.html and index.js) do not need to be hardwired in the `PjBridgeServedFileBasedBrowserBridgeClient>>initMappingOn:andFolder:`. You can use class side methods from `PjApplication` (e.g. `appFullJsFileName`)
- Some demo and test apps have other resources (e.g. PharoJs logo). How do you suggest to map them?
- PharoJS Playground doesn't work for some applications such as `PjThreeJsDemo` when we use `PjBridgeServedFileBasedBrowserBridgeClient`.

Any help with these is welcome.  Of course, we can discuss and help you whenever needed.

**Comment by mattonem** [comment]
Okay so, while running the same suite of test i get a different result... and this is not stable from one execution to the next one. 
Seems to be related to the cache of the Browser which will not reload resources when as they end up all loaded in `web/index.html`.
We could use something like `web/packagename/classname/index.html` to make cache more accurate. 
A better solution would be to open the browser invalidating the cache... but this might require customer implementation for each plateform/browser...
An other option would be to drop a uuid in the url... 

> Filenames (index.html and index.js) do not need to be hardwired in the PjBridgeServedFileBasedBrowserBridgeClient>>initMappingOn:andFolder:. You can use class side methods from PjApplication (e.g. appFullJsFileName)

Agree I'll implement something in those lines.

> Some demo and test apps have other resources (e.g. PharoJs logo). How do you suggest to map them?

In the HTML, image url was referred as `file:/...`. Not that good. I changed that. I think this should not have any effect on the existing BridgeClient

> PharoJS Playground doesn't work for some applications such as PjThreeJsDemo when we use PjBridgeServedFileBasedBrowserBridgeClient.

Looking into that.

**Comment by mattonem** [comment]
>Seems to be related to the cache of the Browser 

Apparently this is not only because of browser cache system. The way Pharo renew TestResource also generates some instability.

**Comment by bouraqadi** [comment]
We also have falky tests that fail or pass kind of randomly. This is seems to be related to a racing condition. But, we didn't manage to fix it yet.

**Comment by bouraqadi** [comment]
@mattonem We run all the tests and they pass, except for `PjSpecialMessagesConversionTest>>#testInlineBlockTempvars`.

After looking at the code, this look related to your last commit that changes `PjTimesRepeatOptimization>>#convertReceiver:args:`.

Why did you want to disable optimizations when there are temporaries?

**Comment by mattonem** [comment]
>Why did you want to disable optimizations when there are temporaries?

That must have been unintentional... Let me clean that up.

**Comment by mattonem** [comment]
That's strange, I don't see any change on `PjTimesRepeatOptimization>>#convertReceiver:args:` in the pull request diff. 
I deactivated opti with temporaries in this PR https://github.com/PharoJS/PharoJS/pull/105 which was closedand never merged as it was a proper fix...
@bouraqadi maybe you need to build a clean image with only that PR into it.

**Pull request merged**
